blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, BlogDeleteView
from django.conf import settings
from django.conf.urls.static import static

app_name = BlogConfig.name

urlpatterns = [
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/<int:pk>/update', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete', BlogDeleteView.as_view(), name='blog_delete')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import (HomeTemplateView, ContactTemplateView, ProductDetailView, ProductListView, ProductCreateView,
                           ProductUpdateView, ProductDeleteView)

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('contacts/', ContactTemplateView.as_view(), name='contacts'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

congig/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("catalog.urls", namespace="gods")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.core.validators import MaxValueValidator

from users.models import User


class Product(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Название продукта",
        help_text="Введите название продукта",
    )
    description = models.TextField(
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
    )
    image = models.ImageField(
        upload_to="catalog/image/",  # Папка для хранения изображений
        blank=True,
        null=True,
        verbose_name="Фото продукта",
        help_text="Загрузите фото продукта",
    )
    category = models.CharField(
        max_length=100,
        verbose_name="Категория",
        help_text="Введите категорию",
    )
    price = models.IntegerField(
        default=0,
        validators=[MaxValueValidator(10000)],
        verbose_name="Цена за продукт",
    )
    created_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата создания",
        help_text="Введите дату создания",
    )
    updated_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата последнего изменения",
        help_text="Введите дату последнего изменения",
    )
    owner = models.ForeignKey(User, verbose_name="Создатель", help_text="Укажите создателя", blank=True, null=True,
                              on_delete=models.SET_NULL)

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "category"]
        permissions = [
            ("can_edit_product", "can edit product"),
            ("can_edit_description", "can edit description")
        ]

    def __str__(self):
        return self.name


# Model representing a Category entity
class Category(models.Model):
    """Represents a category with name and optional description."""

    name = models.CharField(
        max_length=100,
        verbose_name="Название категории",  # Display name for admin panel
        help_text="Введите название категории",  # Tooltip/help text in admin panel
    )
    description = models.TextField(
        blank=True,  # Field is optional
        null=True,  # Allows storing null values
        verbose_name="Описание категории",  # Display name for admin panel
        help_text="Введите описание категории",  # Tooltip/help text in admin panel
    )

    # Meta information for the Category model
    class Meta:
        verbose_name = "Категория"  # Singular name for admin panel
        verbose_name_plural = "Категории"  # Plural name for admin panel

    # String representation of the Category object
    def __str__(self):
        return self.name

catalog/forms.py
from django import forms
from .models import Product

# Список запрещенных слов
FORBIDDEN_WORDS = [
    'казино', 'криптовалюта', 'крипта', 'биржа', 'дешево',
    'бесплатно', 'обман', 'полиция', 'радар'
]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ("owner",)
        fields = ['name', 'description', 'image', 'category', 'price']

    def __init__(self, *args, **kwargs):
        super(ProductForms, self).__init__(*args, **kwargs)
        # Применение классов к каждому полю формы
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    # Валидация названия и описания на запрещенные слова
    def clean_name(self):
        name = self.cleaned_data.get('name').lower()  # Приводим к нижнему регистру
        for word in FORBIDDEN_WORDS:
            if word in name:
                raise forms.ValidationError(f'Название не может содержать слово "{word}".')
        return self.cleaned_data.get('name')

    def clean_description(self):
        description = self.cleaned_data.get('description').lower()  # Приводим к нижнему регистру
        for word in FORBIDDEN_WORDS:
            if word in description:
                raise forms.ValidationError(f'Описание не может содержать слово "{word}".')
        return self.cleaned_data.get('description')

    def clean_price(self):
        price = self.cleaned_data.get('price')

        # Проверяем, что цена не отрицательная
        if price < 0:
            raise forms.ValidationError("Цена не может быть отрицательной")

        return price


class ProductModeratorForms(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['description', 'category', 'category', 'price']

catalog/views.py
# views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from catalog.forms import ProductForm, ProductModeratorForms  # Исправлена ошибка в импорте
from catalog.models import Product


# Главная страница
class HomeTemplateView(TemplateView):
    template_name = 'catalog/home.html'


# Страница контактов
class ContactTemplateView(TemplateView):
    template_name = 'catalog/contacts.html'


# Просмотр списка продуктов
class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'


# Детали продукта
class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'


# Создание нового продукта
class ProductCreateView(CreateView, LoginRequiredMixin):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


# Обновление продукта
class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'

    def get_success_url(self):
        return reverse_lazy('catalog:product_list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm("catalog.can_edit_product") and user.has_perm("catalog.can_edit_descriptions"):
            return ProductModeratorForms
        raise PermissionDenied()


# Удаление продукта
class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'catalog/product_confirm_delete.html'
    success_url = reverse_lazy('catalog:product_list')

catalog/templates/catalog/base.html
{% load static %}

<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Album example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">

    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>

</head>
<body>

<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    {% include 'catalog/includes/inc_menu.html' %}
</header>

<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Продукты</h1>
            </div>
        </div>
    </section>

    {% block content %}
    <h1>{% if object %}Редактировать{% else %}Добавить{% endif %} продукт</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Название</label>
            {{ form.name }}
        </div>

        <div class="form-group">
            <label for="id_description">Описание</label>
            {{ form.description }}
        </div>

        <div class="form-group">
            <label for="id_image">Изображение</label>
            {{ form.image }}
        </div>

        <div class="form-group">
            <label for="id_category">Категория</label>
            {{ form.category }}
        </div>

        <div class="form-group">
            <label for="id_price">Цена</label>
            {{ form.price }}
            {% if form.price.errors %}
            <div class="text-danger">
                {% for error in form.price.errors %}
                <p>{{ error }}</p>
                {% endfor %}
            </div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
    {% endblock %}
</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</body>
</html>

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #343a40; /* Темно-серый фон */
            color: white; /* Белый текст */
        }
        .card {
            background-color: #495057; /* Серый фон карточек */
            color: white;
            border: none; /* Убираем границы */
            border-radius: 8px; /* Округленные углы */
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2); /* Легкая тень */
        }
        .btn-outline-primary {
            color: white;
            border-color: white;
        }
        .btn-outline-primary:hover {
            background-color: white;
            color: #343a40;
        }
        .table-striped > tbody > tr:nth-of-type(odd) {
            --bs-table-accent-bg: #6c757d; /* Более светлый серый */
        }
        footer {
            color: #adb5bd; /* Светло-серый текст */
        }
        h1, h4 {
            color: white;
        }
        .container {
            max-width: 1200px;
        }
    </style>
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-dark border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal text-white">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/product_list/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="/blog/blog_list/">Блоги</a>
        <a class="p-2 btn btn-outline-primary" href="/">Главная</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row">
        <!-- Левая колонка -->
        <div class="col-lg-8 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped text-white">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

        <!-- Правая колонка -->
        <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header text-center">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="form-label">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone" class="form-label">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message" class="form-label">Сообщение</label>
                            <textarea name="message" class="form-control" id="message" placeholder="Ваше сообщение"
                                      rows="4" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary w-100">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<h1>Вы уверены, что хотите удалить этот продукт?</h1>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

catalog/templates/catalog/product_detail.html
<!-- product_detail.html -->
{% extends 'catalog/base.html' %}

{% block content %}
<h1>{{ object.name }}</h1>
<img src="{{ object.image.url }}" alt="{{ object.name }}">
<p>{{ object.description }}</p>
<p>Цена: {{ object.price }}</p>
<p>Категория: {{ object.category }}</p>
<a href="{% url 'catalog:product_update' product.pk %}" class="btn btn-info">Редактировать</a>
<a href="{% url 'catalog:product_delete' object.pk %}" class="btn btn-danger">Удалить</a>
{% endblock %}

catalog/templates/catalog/product_form.html
<!-- catalog/templates/catalog/product_form.html -->
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <h2 class="my-4">Добавить продукт</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Выводим форму -->
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}

<!-- Центрированная кнопка "Добавить продукт" -->
<div class="text-center mb-4">
    {% if user.is_authenticated %}
    <a href="{% url 'catalog:product_create' %}" class="btn btn-primary">Добавить продукт</a>
    {% endif %}
</div>

<!-- Контейнер для карточек продуктов с выравниванием по центру -->
<div class="container">
    <div class="row justify-content-center">
        {% for product in object_list %}
        <div class="col-md-3 mb-4">
            <!-- Карточка продукта -->
            <div class="card">
                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="card-img-top"
                     style="height: 200px; object-fit: cover;">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description|truncatewords:20 }}</p>
                    <a href="{% url 'catalog:product_detail' product.pk %}" class="btn btn-info">Перейти</a>
                    {% if perms.catalog.can_edit_product and perms.catalog.can_edit_description == catalog.owner %}
                    <a href="{% url 'catalog:product_update' product.pk %}" class="btn btn-info">Редактировать</a>
                    <a href="{% url 'catalog:product_delete' product.pk %}" class="btn btn-danger">Удалить</a>
                    {% endif %}

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}